name: Auto Close New Issues

# 监听 Issue 被创建的事件
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-close:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.event.issue.title, 'Registration') || 
      startsWith(github.event.issue.title, 'Submission')
    steps:
      - name: auto-close-issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.issue.number;
            const issue_title = context.payload.issue.title;
            const user_name = context.payload.issue.user.login;
            
            // 根据 issue 类型生成不同的消息
            let message = '';
            if (issue_title.startsWith('Registration')) {
              message = `🤖 注册请求已收到！用户 ${user_name} 的注册信息正在自动处理中...`;
            } else if (issue_title.startsWith('Submission')) {
              message = `🤖 项目提交已收到！用户 ${user_name} 的项目信息正在自动处理中...`;
            }
            
            await github.rest.issues.update({
              owner,
              repo,
              issue_number,
              state: 'closed'
            });
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message
            });
