name: Update Submission Status & Sync README

on:
  push:
    branches:
      - main
    paths:
      - 'submission/*/**'
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'submission/*/**'
  workflow_dispatch:

jobs:
  update-and-sync:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update submission status table
        run: |
          node -e "require('./scripts/submission_table').updateSubmissionTable()"

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          if ! git diff --quiet README.md; then
            git add README.md
            git commit -m "🤖 Auto-update: Update submission status table"
            git pull --rebase origin main
            git push
            echo "✅ Submission status table updated and committed"
          else
            echo "ℹ️ No changes to commit"
          fi